services:
  mongo:
    image: mongo:6.0
    container_name: mongo_db_mocky
    restart: always
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  app:
    build:
      context: .
      dockerfile: docker_images/deploy/Dockerfile.deploy
    container_name: mocky
    environment:
      ENVIRONMENT: development
      MONGO_DSN: mongodb://root:example@mongo_db_mocky:27017
      ROOT_PATH: 
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  testing:
    depends_on:
      - mongo
    build:
      context: .
      dockerfile: docker_images/testing/Dockerfile.testing
    container_name: mocky-testing
