# Etapa única para test
FROM golang:1.24-alpine AS tester
WORKDIR /app

# Dependencias necesarias
RUN apk add --no-cache git build-base

# Copiar go.mod y go.sum y descargar deps
COPY go.mod go.sum ./
RUN go mod download

# Copiar todo el código
COPY . .

# Comando por defecto: ejecutar todos los tests
CMD ["go", "test", "-v", "-race", "-cover", "./..."]
